create table if not exists public.memes (
    id bigint generated by default as identity primary key,
    guild_id bigint not null,
    keyword text not null,
    match_type text not null check (match_type in ('partial', 'exact')),
    image_path text not null,
    created_by bigint not null,
    created_at timestamptz not null default now(),
    enabled boolean not null default true,
    trigger_count bigint not null default 0,
    reading text,
    reading_updated_by bigint,
    reading_updated_at timestamptz,
    unique (guild_id, keyword, match_type)
);

alter table public.memes
    add column if not exists reading text;

alter table public.memes
    add column if not exists reading_updated_by bigint;

alter table public.memes
    add column if not exists reading_updated_at timestamptz;

alter table public.memes enable row level security;

grant select, insert, update, delete on table public.memes
    to service_role;

grant usage, select on sequence public.memes_id_seq
    to service_role;

create index if not exists idx_memes_guild_enabled
    on public.memes (guild_id, enabled);

create index if not exists idx_memes_guild_keyword
    on public.memes (guild_id, keyword);

create or replace function public.increment_meme_trigger_count(
    p_guild_id bigint,
    p_meme_id bigint
)
returns void
language sql
set search_path = ''
as $$
    update public.memes
    set trigger_count = trigger_count + 1
    where guild_id = p_guild_id and id = p_meme_id;
$$;

revoke execute on function public.increment_meme_trigger_count(bigint, bigint)
    from public, anon, authenticated;

grant execute on function public.increment_meme_trigger_count(bigint, bigint)
    to service_role;

insert into storage.buckets (
    id,
    name,
    public,
    file_size_limit,
    allowed_mime_types
)
values (
    'memes',
    'memes',
    false,
    52428800,
    array[
        'image/jpeg',
        'image/png',
        'image/webp',
        'image/gif'
    ]
)
on conflict (id) do nothing;
